# Shared host-portability helpers for the tests/ shell suite.
#
# Sourced, never executed. Keep every function POSIX-sh clean: some scripts run
# under `sh`, and the whole point of this file is to work on the hosts that
# behave least like the developer's Mac.
#
# See tests/run.sh for the wrapper that installs the shims for a whole script.

# Echo the name of a Python interpreter that ACTUALLY RUNS, or fail (rc 1).
#
# The check is deliberately "execute it", not `command -v`: Windows ships an App
# Execution Alias at WindowsApps/python3 that exists, is executable, and exits
# 49 after advertising the Microsoft Store. A PATH check accepts it, and then
# every `... | python3 -c ...` in the suite yields an empty string that reads as
# an empty server response.
mlxserve_resolve_python() {
    for _mlxserve_py in python3 python py; do
        command -v "$_mlxserve_py" >/dev/null 2>&1 || continue
        if "$_mlxserve_py" -c '' >/dev/null 2>&1; then
            echo "$_mlxserve_py"
            unset _mlxserve_py
            return 0
        fi
    done
    unset _mlxserve_py
    echo "portable_env: no working python interpreter on PATH" >&2
    return 1
}

# Create <dir> holding a `python3` that forwards to whatever interpreter
# actually runs here, and echo <dir>. Callers PREPEND it to PATH.
#
# A shim rather than a rewrite of the call sites: 140 scripts spell the
# interpreter `python3` in 645 places, and they are the same scripts that run
# unmodified on macOS. Shadowing the broken name costs one directory; editing
# every call site costs a diff nobody can review against a real failure.
mlxserve_make_python_shim() {
    _mlxserve_dir=$1
    _mlxserve_real=$(mlxserve_resolve_python) || { unset _mlxserve_dir _mlxserve_real; return 1; }
    # Already the working name and nothing to shadow — still emit the shim so
    # the caller's PATH handling has one shape.
    mkdir -p "$_mlxserve_dir" || { unset _mlxserve_dir _mlxserve_real; return 1; }
    _mlxserve_abs=$(command -v "$_mlxserve_real")
    {
        echo '#!/bin/sh'
        echo "# Generated by tests/lib/portable_env.sh — shadows a non-working python3."
        echo "exec \"$_mlxserve_abs\" \"\$@\""
    } > "$_mlxserve_dir/python3"
    chmod +x "$_mlxserve_dir/python3"
    echo "$_mlxserve_dir"
    unset _mlxserve_dir _mlxserve_real _mlxserve_abs
    return 0
}

# Echo <path> in the form the SERVER understands, for embedding in a request
# body or any other payload the shell does not get to rewrite.
#
# Git Bash converts POSIX paths to Windows ones on the way into a native
# binary's argv, so `--model-dir /tmp/x` arrives as C:/Users/.../Temp/x and
# works. A path inside a curl JSON body gets no such treatment: it arrives as
# the literal "/tmp/x", which no Windows process can open, and the server
# answers "No loadable model directory at that path" -- a correct answer to a
# question the test did not mean to ask (test_model_rescan, 2026-08-20).
#
# On macOS and Linux there is nothing to convert and this is the identity.
mlxserve_host_path() {
    _mlxserve_p=$1
    if command -v cygpath >/dev/null 2>&1; then
        # -m gives C:/style/forward/slashes: valid for the Windows API and, being
        # backslash-free, safe to paste straight into JSON.
        cygpath -m "$_mlxserve_p" 2>/dev/null || echo "$_mlxserve_p"
    else
        echo "$_mlxserve_p"
    fi
    unset _mlxserve_p
}

# Was this mlx-serve built WITH MLX (rc 0) or is it the portable, GGUF-only
# configuration (rc 1)?
#
# Off Apple silicon MLX has no build at all, so media generation, ds4, ANE and
# the safetensors loader are all absent BY DESIGN and refuse by name. A test
# that exercises one of them is not failing there, it is inapplicable -- and a
# red result reads as a broken feature. The marker is the one `--version`
# prints from transformer_stub.zig, so it tracks the BUILD rather than the
# host: a Mac configured with -Dgguf-only answers the same way, which is the
# whole point of being able to check that configuration on a Mac.
mlxserve_has_mlx() {
    _mlxserve_bin=${1:-./zig-out/bin/mlx-serve}
    if ! "$_mlxserve_bin" --version 2>/dev/null | grep -q "built without MLX"; then
        unset _mlxserve_bin
        return 0
    fi
    unset _mlxserve_bin
    return 1
}

# Echo this machine's routable IPv4 address, or nothing (rc 1) when it has
# none. Used by tests that need a NON-loopback address: LAN discovery and the
# share gate are both meaningless over 127.0.0.1.
#
# `ipconfig getifaddr en0` is macOS-only, and it was the only probe here — so
# every such test skipped on Linux and Windows with "offline Mac", which reads
# as a precondition rather than as a missing shim. The interfaces are named
# differently on every host (en0 / eth0 / "Ethernet 2"), so the last resort
# does not name one at all: a UDP socket "connected" to an off-box address
# sends nothing but makes the kernel pick the outbound interface, and its local
# address is that interface's. That works identically on all three hosts.
mlxserve_lan_ip() {
    _mlxserve_ip=$(ipconfig getifaddr en0 2>/dev/null || ipconfig getifaddr en1 2>/dev/null || true)
    if [ -z "$_mlxserve_ip" ] && command -v ip >/dev/null 2>&1; then
        _mlxserve_ip=$(ip route get 1.1.1.1 2>/dev/null | awk '{for(i=1;i<=NF;i++) if($i=="src"){print $(i+1); exit}}')
    fi
    if [ -z "$_mlxserve_ip" ]; then
        _mlxserve_py=$(mlxserve_resolve_python 2>/dev/null) || _mlxserve_py=""
        if [ -n "$_mlxserve_py" ]; then
            _mlxserve_ip=$("$_mlxserve_py" -c 'import socket
s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
try:
    s.connect(("1.1.1.1", 53))
    print(s.getsockname()[0])
except Exception:
    pass
finally:
    s.close()' 2>/dev/null)
        fi
        unset _mlxserve_py
    fi
    case "$_mlxserve_ip" in
        ""|127.*|0.0.0.0) unset _mlxserve_ip; return 1 ;;
    esac
    echo "$_mlxserve_ip"
    unset _mlxserve_ip
    return 0
}
